### ISSUE TITLE
schema.sql是干啥的;貌似没有调用

### ISSUE THREAD

**Issue by FENVL** [EalenXie/springboot-quartz-simple#1]
大佬; schema.sql是干啥的;貌似没有调用

**Comment by FENVL** [comment]
我实际项目中也看到了类似的表, 配了一个些trigger和job,  所以, 大佬; 为什么不适用注解(@Schedule)方式, 岂不是更简单,  为什么要搞些表自定义trigger和job, 有什么好处??

**Comment by EalenXie** [comment]
> 大佬; schema.sql是干啥的;貌似没有调用

数据源选择的是H2，springboot会自动读取resource/schema.sql 初始化数据库。

**Comment by EalenXie** [comment]
> 我实际项目中也看到了类似的表, 配了一个些trigger和job, 所以, 大佬; 为什么不适用注解(@schedule)方式, 岂不是更简单, 为什么要搞些表自定义trigger和job, 有什么好处??

`@schedule`是spring自带的调度，和quartz相比，功能较少(不支持动态启动停止)，默认不支持集群。
